"""add liked column to recipe_feedbacks

Revision ID: 3eacbf670302
Revises: 002_add_pgvector_support
Create Date: 2025-06-30 05:39:38.260335+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3eacbf670302"
down_revision: Union[str, Sequence[str], None] = "002_add_pgvector_support"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recipe_feedbacks", sa.Column("liked", sa.Boolean(), nullable=True))
    op.alter_column(
        "users",
        "email_notifications_enabled",
        existing_type=sa.BOOLEAN(),
        nullable=True,
    )
    op.alter_column(
        "users", "weekly_planning_reminder", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "users", "reminder_day_of_week", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "users", "reminder_time", existing_type=postgresql.TIME(), nullable=True
    )
    op.alter_column("users", "timezone", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "timezone", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "users", "reminder_time", existing_type=postgresql.TIME(), nullable=False
    )
    op.alter_column(
        "users", "reminder_day_of_week", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "users", "weekly_planning_reminder", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "users",
        "email_notifications_enabled",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )
    op.drop_column("recipe_feedbacks", "liked")
    # ### end Alembic commands ###
